#!/usr/bin/env bash

sudo add-apt-repository ppa:ondrej/php5

# unattended upgrade, avoids the garbled text
unset UCF_FORCE_CONFFOLD
export UCF_FORCE_CONFFNEW=YES
ucf --purge /boot/grub/menu.lst

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade


#upgrade PHP to 5.5
sudo apt-get install php5 -y


# install console and git, memcached
apt-get install -y php5-cli git curl
sudo apt-get install php5-memcached -y

# fix PHP Warning: Module 'memcache' already loaded in Unknown on line 0
sudo echo ";extension=memcache.so" > /etc/php5/cli/conf.d/memcache.ini


#install mysql
# sudo apt-get install mysql-server php5-mysql
# sudo mysql_install_db
# sudo /usr/bin/mysql_secure_installation

#install nginx
# echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/nginx-stable.list
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C300EE8C
# sudo apt-get update
# sudo apt-get install nginx
# sudo service nginx start

#add vagrant user to www-data group
sudo usermod -G www-data vagrant

#configure default site
sudo rm /etc/nginx/sites-available/default
sudo cp /vagrant/configs/default.site /etc/nginx/sites-available/default

#copy site contents
cp -R /vagrant/sites/bamp.dev /home/vagrant
sudo nginx -s reload


#install php
#sudo apt-get install php5-fpm

# edit and adjust the config to cgi.fix_pathinfo=0
#sudo nano /etc/php5/fpm/php.ini

# edit and make sure  listen = /var/run/php5-fpm.sock
#sudo nano /etc/php5/fpm/pool.d/www.conf

# Uncomment all permission lines, like:
# listen.owner = www-data
# listen.group = www-data
# listen.mode = 0660

# sudo service php5-fpm restart



# install mongodb
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
# echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
# sudo apt-get update
# sudo apt-get install -y mongodb-org

#install php driver
# sudo apt-get install php-pear php5-dev make
# sudo pecl install mongo
# sudo nano /etc/php5/fpm/php.ini
# add extension=mongo.so
# sudo service php5-fpm restart


# install supervisord & beanstalkd
# sudo apt-get install -y supervisor
# sudo aptitude install -y beanstalkd

# sudo iptables -I INPUT -p tcp --dport 3306 -j ACCEPT
# sudo iptables-save

# sudo iptables -I INPUT -p tcp --dport 27017 -j ACCEPT
# sudo iptables-save

# install mcrypt
# sudo apt-get install -y php5-mcrypt
# sudo php5enmod mcrypt


# Install Composer
# curl -sS https://getcomposer.org/installer | php
# sudo mv composer.phar /usr/local/bin/composer

mysqladmin -u root -p'tsv3' password 'buonzz'

apt-get install pwgen -y

MYSQL_ROOT_PASS="buonzz" # Put yours

PHPMYADMIN_DIR="pmasecret879"      # You don't want script kiddies playing  
                                   # with your default phpMyAdmin install.
AUTOGENERATED_PASS=`pwgen -c -1 20`

echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections

apt-get -y install phpmyadmin

# Regex FTW!
sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf

php5enmod mcrypt # Needs to be activated manually (that's an issue for Ubuntu 14.04)

service apache2 reload



sudo ln -s /usr/share/phpmyadmin /home/vagrant/bamp.dev/public/phpmyadmin

chmod 777 /home/vagrant/bamp.dev/public/beanstalk_console/storage.json


sudo apt-get install -y php5-memcache
sudo apt-get install -y memcached
sudo apt-get install -y php-pear
sudo apt-get install -y build-essential
sudo pecl install memcache
echo "extension=memcache.so" | sudo tee /etc/php5/conf.d/memcache.ini
sudo service php5-fpm restart

#try to fix weird issue about vagrant getting kicked out of sudoer
echo %vagrant ALL=NOPASSWD:ALL > /etc/sudoers.d/vagrant
chmod 0440 /etc/sudoers.d/vagrant
usermod -a -G sudo vagrant

echo "START=yes" | sudo tee /etc/default/beanstalkd
sudo service beanstalkd start


#disable the /HOME/USERNAME/.NANO_HISTORY: PERMISSION DENIED
sudo rm .nano_history


sudo apt-get clean
#sudo dd if=/dev/zero of=/EMPTY bs=1M
#sudo rm -f /EMPTY
cat /dev/null > ~/.bash_history && history -c
